name: Django CI

on:
  push:
    branches: [ "master", "deploy" ]
  pull_request:
    branches: [ "master", "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.4
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -r requirements.txt
        
    - name: Create env file
      run: |
        echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env
      
    - name: Create client_id.json
      run: |
        mkdir secrets
        echo "${{secrets.GOOGLE_OAUTH_CLIENT_JSON}}" >> secrets/client_id.json

    - name: Coverage Report and Test
      run: |
        coverage run manage.py test
        coverage combine
        coverage report
